### ISSUE TITLE
Building binary fails on untrusted package

### ISSUE THREAD

**Issue by asmodehn** [mikeferguson/buildbot-ros#58]
I m trying to build a binary from ecl_sigslots. 
Here is the log : 

```
Detected git-buildpackage version (0, 6, 9)
Running git-buildpackage command: ['git-buildpackage', '--git-pbuilder', '--git-export=WC', '--git-upstream-tree=TAG', '--git-upstream-tag=debian/ros-indigo-ecl-sigslots_0.61.3-0_trusty', '--git-export-dir=/home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild', '-uc', '-us', '--git-ignore-branch', '--git-ignore-new', '--git-verbose', '--git-dist=trusty', '--git-arch=amd64']
gbp:debug: ['git', 'rev-parse', '--show-cdup']
gbp:debug: ['git', 'rev-parse', '--is-bare-repository']
gbp:debug: /bin/true [] []
gbp:debug: ['git', 'symbolic-ref', 'HEAD']
gbp:debug: ['git', 'add', '-f', '/home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild/build']
gbp:debug: ['git', 'write-tree']
gbp:debug: ['git', 'ls-tree', '6e02a0bc0314cce67d357b71b32570c8dcc1b374']
gbp:debug: ['git', 'show', '--pretty=medium', '6e02a0bc0314cce67d357b71b32570c8dcc1b374:debian/source/format']
gbp:debug: ['git', 'show', '--pretty=medium', '6e02a0bc0314cce67d357b71b32570c8dcc1b374:debian/changelog']
gbp:debug: ['git', 'show-ref', 'refs/heads/pristine-tar']
gbp:debug: ['git', 'ls-tree', 'debian/ros-indigo-ecl-sigslots_0.61.3-0_trusty']
gbp:info: ros-indigo-ecl-sigslots_0.61.3-0-20150930-0200.orig.tar.gz does not exist, creating from 'debian/ros-indigo-ecl-sigslots_0.61.3-0_trusty'
gbp:debug: Building upstream tarball with compression 'gzip -9'
gbp:info: Exporting 'WC' to '/home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild/ros-indigo-ecl-sigslots-tmp'
gbp:debug: ['git', 'show', '--pretty=medium', '6e02a0bc0314cce67d357b71b32570c8dcc1b374:debian/source/format']
gbp:info: Moving '/home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild/ros-indigo-ecl-sigslots-tmp' to '/home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild/ros-indigo-ecl-sigslots-0.61.3-0-20150930-0200'
gbp:debug: ['git', 'show', '--pretty=medium', '6e02a0bc0314cce67d357b71b32570c8dcc1b374:debian/source/format']
gbp:debug: git-pbuilder ['-uc', '-us'] []
Building with cowbuilder for distribution trusty, architecture amd64
W: /home/buildbot/.pbuilderrc does not exist
I: using cowbuilder as pbuilder
dpkg-buildpackage: source package ros-indigo-ecl-sigslots
dpkg-buildpackage: source version 0.61.3-0-20150930-0200-+0900trusty
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by BuildBot Yujin <buildbot@asmodehn.yujin.com>
 dpkg-source --before-build ros-indigo-ecl-sigslots-0.61.3-0-20150930-0200
 fakeroot debian/rules clean
dh  clean
   dh_testdir
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
   dh_auto_clean
   dh_clean
Unknown option: buildsystem
dh_clean: warning: ignored unknown options in DH_OPTIONS
	rm -f debian/ros-indigo-ecl-sigslots.substvars
	rm -f debian/ros-indigo-ecl-sigslots.*.debhelper
	rm -rf debian/ros-indigo-ecl-sigslots/
	rm -f debian/*.debhelper.log
	rm -f debian/files
	find .  \( \( -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
	rm -f *-stamp
 dpkg-source -b ros-indigo-ecl-sigslots-0.61.3-0-20150930-0200
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building ros-indigo-ecl-sigslots using existing ./ros-indigo-ecl-sigslots_0.61.3-0-20150930-0200.orig.tar.gz
dpkg-source: info: building ros-indigo-ecl-sigslots in ros-indigo-ecl-sigslots_0.61.3-0-20150930-0200-+0900trusty.debian.tar.gz
dpkg-source: info: building ros-indigo-ecl-sigslots in ros-indigo-ecl-sigslots_0.61.3-0-20150930-0200-+0900trusty.dsc
 dpkg-genchanges -S >../ros-indigo-ecl-sigslots_0.61.3-0-20150930-0200-+0900trusty_source.changes
dpkg-genchanges: including full source code in upload
 dpkg-source --after-build ros-indigo-ecl-sigslots-0.61.3-0-20150930-0200
dpkg-buildpackage: full upload (original source is included)
 -> Copying COW directory
  forking: rm -rf /var/cache/pbuilder/build//cow.11978 
  forking: cp -al /var/cache/pbuilder/base-trusty-amd64.cow /var/cache/pbuilder/build//cow.11978 
I: removed stale ilistfile /var/cache/pbuilder/build//cow.11978/.ilist
  forking: chroot /var/cache/pbuilder/build//cow.11978 cowdancer-ilistcreate /.ilist find . -xdev -path ./home -prune -o \( \( -type l -o -type f \) -a -links +1 -print0 \) | xargs -0 stat --format '%d %i ' 
 -> Invoking pbuilder
  forking: pbuilder build --debbuildopts  --debbuildopts   '-uc' '-us' --hookdir /home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild/hooks --override-config --buildplace /var/cache/pbuilder/build//cow.11978 --buildresult /home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild --debbuildopts   '-uc' '-us' --no-targz --internal-chrootexec chroot /var/cache/pbuilder/build//cow.11978 cow-shell /home/buildbot/rosbuilder1/ecl_core_indigo_trusty_amd64_debbuild/ros-indigo-ecl-sigslots_0.61.3-0-20150930-0200-+0900trusty.dsc 
W: /home/buildbot/.pbuilderrc does not exist
I: Running in no-targz mode
I: using fakeroot in build.
I: Current time: Wed Sep 30 02:00:20 KST 2015
I: pbuilder-time-stamp: 1443546020
I: copying local configuration
W: No local /etc/hostname to copy, relying on /var/cache/pbuilder/build/cow.11978/etc/hostname to be correct
I: Installing apt-lines
I: mounting /proc filesystem
I: mounting /run/shm filesystem
I: mounting /dev/pts filesystem
I: policy-rc.d already exists
I: Obtaining the cached apt archive contents
I: Installing the build-deps
I: user script /var/cache/pbuilder/build/cow.11978/tmp/hooks/D05deps starting
Ign http://localhost trusty InRelease
Ign http://localhost trusty Release.gpg
Get:1 http://localhost trusty Release [1596 B]
Get:2 http://localhost trusty/main amd64 Packages [847 B]
Ign http://localhost trusty/main Translation-en
Ign http://kr.archive.ubuntu.com trusty InRelease
Hit http://kr.archive.ubuntu.com trusty Release.gpg
Hit http://kr.archive.ubuntu.com trusty Release
Hit http://kr.archive.ubuntu.com trusty/main amd64 Packages
Hit http://kr.archive.ubuntu.com trusty/main Translation-en
Get:3 http://packages.ros.org trusty InRelease [4040 B]
Get:4 http://packages.ros.org trusty/main amd64 Packages [563 kB]
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Get:5 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Ign http://packages.ros.org trusty/main Translation-en
Hit http://archive.ubuntu.com trusty Release
Get:6 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Get:7 http://archive.ubuntu.com trusty-updates/main amd64 Packages [627 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [319 kB]
Get:9 http://archive.ubuntu.com trusty-updates/main Translation-en [304 kB]
Get:10 http://archive.ubuntu.com trusty-updates/universe Translation-en [168 kB]
Fetched 2051 kB in 10s (190 kB/s)
Reading package lists...
I: user script /var/cache/pbuilder/build/cow.11978/tmp/hooks/D05deps finished
 -> Attempting to satisfy build-dependencies
 -> Creating pbuilder-satisfydepends-dummy package
Package: pbuilder-satisfydepends-dummy
Version: 0.invalid.0
Architecture: amd64
Maintainer: Debian Pbuilder Team <pbuilder-maint@lists.alioth.debian.org>
Description: Dummy package to satisfy dependencies with aptitude - created by pbuilder
 This package was created automatically by pbuilder to satisfy the
 build-dependencies of the package being currently built.
Depends: debhelper (>= 9.0.0), ros-indigo-catkin, ros-indigo-ecl-config, ros-indigo-ecl-license, ros-indigo-ecl-threads
dpkg-deb: building package `pbuilder-satisfydepends-dummy' in `/tmp/satisfydepends-aptitude/pbuilder-satisfydepends-dummy.deb'.
Selecting previously unselected package pbuilder-satisfydepends-dummy.
(Reading database ... 12756 files and directories currently installed.)
Preparing to unpack .../pbuilder-satisfydepends-dummy.deb ...
Unpacking pbuilder-satisfydepends-dummy (0.invalid.0) ...
dpkg: pbuilder-satisfydepends-dummy: dependency problems, but configuring anyway as you requested:
 pbuilder-satisfydepends-dummy depends on debhelper (>= 9.0.0); however:
  Package debhelper is not installed.
 pbuilder-satisfydepends-dummy depends on ros-indigo-catkin; however:
  Package ros-indigo-catkin is not installed.
 pbuilder-satisfydepends-dummy depends on ros-indigo-ecl-config; however:
  Package ros-indigo-ecl-config is not installed.
 pbuilder-satisfydepends-dummy depends on ros-indigo-ecl-license; however:
  Package ros-indigo-ecl-license is not installed.
 pbuilder-satisfydepends-dummy depends on ros-indigo-ecl-threads; however:
  Package ros-indigo-ecl-threads is not installed.

Setting up pbuilder-satisfydepends-dummy (0.invalid.0) ...
Reading package lists...
Building dependency tree...
Reading state information...
Initializing package states...
Writing extended state information...
The following NEW packages will be installed:
  bsdmainutils{a} cmake{a} cmake-data{a} debhelper{a} dh-apparmor{a} 
  docutils-common{a} file{a} gettext{a} gettext-base{a} groff-base{a} 
  intltool-debian{a} libarchive13{a} libasn1-8-heimdal{a} libasprintf0c2{a} 
  libcroco3{a} libcurl3{a} libgcrypt11{a} libglib2.0-0{a} libgnutls26{a} 
  libgpg-error0{a} libgssapi-krb5-2{a} libgssapi3-heimdal{a} 
  libgtest-dev{a} libhcrypto4-heimdal{a} libheimbase1-heimdal{a} 
  libheimntlm0-heimdal{a} libhx509-5-heimdal{a} libk5crypto3{a} 
  libkeyutils1{a} libkrb5-26-heimdal{a} libkrb5-3{a} libkrb5support0{a} 
  libldap-2.4-2{a} liblzo2-2{a} libmagic1{a} libnettle4{a} libp11-kit0{a} 
  libpipeline1{a} libroken18-heimdal{a} librtmp0{a} libsasl2-2{a} 
  libsasl2-modules-db{a} libtasn1-6{a} libunistring0{a} libwind0-heimdal{a} 
  libxml2{a} man-db{a} po-debconf{a} python-catkin-pkg{a} 
  python-dateutil{a} python-docutils{a} python-empy{a} python-nose{a} 
  python-pkg-resources{a} python-roman{a} ros-indigo-catkin{a} 
  ros-indigo-ecl-build{a} ros-indigo-ecl-concepts{a} 
  ros-indigo-ecl-config{a} ros-indigo-ecl-errors{a} 
  ros-indigo-ecl-exceptions{a} ros-indigo-ecl-license{a} 
  ros-indigo-ecl-mpl{a} ros-indigo-ecl-threads{a} ros-indigo-ecl-time{a} 
  ros-indigo-ecl-time-lite{a} ros-indigo-ecl-type-traits{a} 
  ros-indigo-ecl-utilities{a} sgml-base{a} xml-core{a} 
0 packages upgraded, 70 newly installed, 0 to remove and 80 not upgraded.
Need to get 6358 B/13.7 MB of archives. After unpacking 57.0 MB will be used.
WARNING: untrusted versions of the following packages will be installed!

Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  ros-indigo-ecl-mpl 

Do you want to ignore this warning and proceed anyway?
To continue, enter "Yes"; to abort, enter "No": Abort.
E: pbuilder-satisfydepends failed.
I: Copying back the cached apt archive contents
I: unmounting dev/pts filesystem
I: unmounting run/shm filesystem
I: unmounting proc filesystem
 -> Cleaning COW directory
  forking: rm -rf /var/cache/pbuilder/build//cow.11978 
gbp:error: Couldn't run 'git-pbuilder -uc -us': git-pbuilder returned 1
No protocol specified
program finished with exit code 1
elapsedTime=15.028819
```

I m wondering if this is due to cowbuilder missing some information ?
or perhaps because of one of the warning ?

As far as I know this package installs fine with apt-get on a usual system, so I suspect it is only a symptom of something else going wrong...

Cheers.

**Comment by asmodehn** [comment]
Note that I didn't sign the repository with gpg.
Is it supposed to be mandatory ?

**Comment by asmodehn** [comment]
- I tried to sign my repository. same issue, no change.
- I tried to add the apt company repo, just in case it mattered, but nothing changes.

This package is actually in public rosdistro https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml so I m not sure why the buildscript thinks it is "untrusted"...

So the "targets _config" part of my (source/doc/release)-build configuration is now : 
```
targets:
  _config:
    apt_mirrors:
    - http://localhost/building/ubuntu DISTRO main  # local apt mirror for testing buildbot-ros locally
    - http://packages.yujinrobot.com/yujin/ubuntu trusty main  # company apt-mirror for some dependencies ( will transit to use this one later )
    - http://packages.ros.org/ros/ubuntu DISTRO main
    - http://archive.ubuntu.com/ubuntu DISTRO main universe
    - http://archive.ubuntu.com/ubuntu DISTRO-updates main universe
    apt_keys:
    - http://packages.ros.org/ros.key
    - http://packages.yujinrobot.com/yujin.key  # company apt key
    - file:///home/alexv/alexv.gpg  # local apt key
```

**Comment by asmodehn** [comment]
So recently I decided to completely clean and re-setup the building repo and my buildbot master / slave configuration.

After only one mistake during the setup from my side ( addressed here https://github.com/mikeferguson/buildbot-ros/pull/59 ), I finally got it to run. The untrusted package error has disappeared.

So I am wondering if the cowbuilder-update script maybe doesn't support adding repositories / keys after it was run the first time ? This seems strange, but thats my only guess at the moment...

When I had a error because of virtual env activation, I could see all my keys in the log : 
```
Upon execvpe cowbuilder-update.py ['cowbuilder-update.py', 'trusty', 'amd64', 'http://packages.ros.org/ros.key', 'http://packages.yujinrobot.com/yujin.key', 'http://localhost/building/buildbot.key'] in environment id 139797831138112
:Traceback (most recent call last):
  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
    environment)
  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
    os.execvpe(executable, args, environment)
  File "/home/buildbot/.virtualenvs/buildbot-env/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/home/buildbot/.virtualenvs/buildbot-env/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

Now that it works well, somehow I cannot check which keys are being imported. Here is the beginning of a working log : 
```
 -> Copying COW directory
  forking: rm -rf /var/cache/pbuilder/build//cow.30067 
  forking: cp -al /var/cache/pbuilder/base-trusty-amd64.cow /var/cache/pbuilder/build//cow.30067 
I: removed stale ilistfile /var/cache/pbuilder/build//cow.30067/.ilist
 -> Invoking pbuilder
  forking: pbuilder execute --bindmounts /tmp/ecl_tools_indigo_docbuild --override-config --othermirror deb http://localhost/building/ubuntu trusty main |
deb http://packages.yujinrobot.com/yujin/ubuntu trusty main |
deb http://packages.ros.org/ros/ubuntu trusty main |
deb http://archive.ubuntu.com/ubuntu trusty main universe |
deb http://archive.ubuntu.com/ubuntu trusty-updates main universe | --buildplace /var/cache/pbuilder/build//cow.30067 --no-targz --internal-chrootexec chroot /var/cache/pbuilder/build//cow.30067 cow-shell /home/buildbot/rosbuilder1/ecl_tools_indigo_docbuild/docbuild.py /tmp/ecl_tools_indigo_docbuild indigo 
W: /home/buildbot/.pbuilderrc does not exist
I: Running in no-targz mode
I: copying local configuration
W: No local /etc/hostname to copy, relying on /var/cache/pbuilder/build/cow.30067/etc/hostname to be correct
I: Installing apt-lines
I: mounting /proc filesystem
I: mounting /run/shm filesystem
I: mounting /dev/pts filesystem
I: Mounting /tmp/ecl_tools_indigo_docbuild
I: policy-rc.d already exists
I: Obtaining the cached apt archive contents
Executing command "apt-get update"
Ign http://localhost trusty InRelease
Ign http://localhost trusty Release.gpg
Get:1 http://localhost trusty Release [1584 B]
Get:2 http://localhost trusty/main amd64 Packages [20 B]
Ign http://localhost trusty/main Translation-en
Get:3 http://packages.yujinrobot.com trusty InRelease [2185 B]
Ign http://kr.archive.ubuntu.com trusty InRelease
Get:4 http://packages.yujinrobot.com trusty/main amd64 Packages [3924 B]
Hit http://kr.archive.ubuntu.com trusty Release.gpg
Hit http://kr.archive.ubuntu.com trusty Release
Ign http://packages.yujinrobot.com trusty/main Translation-en
Hit http://kr.archive.ubuntu.com trusty/main amd64 Packages
Hit http://kr.archive.ubuntu.com trusty/main Translation-en
Get:5 http://packages.ros.org trusty InRelease [4040 B]
Get:6 http://packages.ros.org trusty/main amd64 Packages [563 kB]
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Get:7 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Hit http://archive.ubuntu.com trusty Release
Get:8 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
Ign http://packages.ros.org trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Get:9 http://archive.ubuntu.com trusty-updates/main amd64 Packages [627 kB]
Get:10 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [320 kB]
Get:11 http://archive.ubuntu.com trusty-updates/main Translation-en [305 kB]
Get:12 http://archive.ubuntu.com trusty-updates/universe Translation-en [169 kB]
Fetched 2059 kB in 6s (308 kB/s)
Reading package lists...
Executing command "apt-get install --yes ros-indigo-ros ros-indigo-rosdoc-lite doxygen python-epydoc python-sphinx graphviz"
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
[...]
```

**Comment by asmodehn** [comment]
Thinking about it, it could have been because previously my gpg key was not created by the buildbot user, and therefore was not known to buildbot master and slave...

**Comment by mikeferguson** [comment]
This appears to be some setup issue -- I've know for a fact that we can add keys after first creation of the buildbot (i've used it a number of times). Closing this as not really actionable
