### ISSUE TITLE
Building only with doc and source does not seem possible

### ISSUE THREAD

**Issue by asmodehn** [mikeferguson/buildbot-ros#60]
Is this supposed to work ?

I tried it this way to avoid having to do a full bloom-release before building. Just to check buildbot could build the source and doc before doing the first release.

the rosdistro at that time was https://github.com/yujinrobot/rosdistro/commit/66bfc4e1f7286961271db99d65d0934223fa8843

However It failed with : 
```
2015-10-12 12:24:35+0900 [-] error while parsing config file:
	Traceback (most recent call last):
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/buildbot/master.py", line 189, in startService
	    self.configFileName)
	--- <exception caught here> ---
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/buildbot/config.py", line 156, in loadConfig
	    exec f in localDict
	  File "/home/buildbot/buildbot-ros/master.cfg", line 88, in <module>
	    DOC_JOBS = docbuilders_from_rosdistro(c, oracle, dist, BUILDERS)
	  File "/home/buildbot/buildbot-ros/buildbot_ros_cfg/distro.py", line 313, in docbuilders_from_rosdistro
	    oracle.getDocTrigger(name, distro)))
	  File "/home/buildbot/buildbot-ros/buildbot_ros_cfg/distro.py", line 113, in getDocTrigger
	    i = self.build_order[dist_name]['doc_jobs'].index(repo_name)
	exceptions.ValueError: 'gopher_msgs' is not in list
	
2015-10-12 12:24:35+0900 [-] Configuration Errors:
2015-10-12 12:24:35+0900 [-]   error while parsing config file: 'gopher_msgs' is not in list (traceback in logfile)
2015-10-12 12:24:35+0900 [-] Halting master.
2015-10-12 12:24:35+0900 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 364, in startReactor
	    self.config, oldstdout, oldstderr, self.profiler, reactor)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 285, in runReactorWithLogging
	    reactor.run()
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
	    f(*a, **kw)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 581, in stop
	    "Can't stop reactor that isn't running.")
	twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
	
2015-10-12 12:24:35+0900 [-] Main loop terminated.
2015-10-12 12:24:35+0900 [-] Server Shut Down.

```

So I m thinking the docbuild job depends on a release to be there already ?

**Comment by asmodehn** [comment]
Note that removing the doc: section is enough to get buildbot to start and building only the testbuild from the source section is definitely working.

**Comment by mikeferguson** [comment]
I've added some documentation related to this (it was previously only documented in the code). Doc jobs do require dependency calculation (which, in rosdistro, is based on the released package.xmls), whereas test builds do not require any dependency resolution.
