### ISSUE TITLE
Improve error message when package xml returns empty.

### ISSUE THREAD

**Issue by asmodehn** [mikeferguson/buildbot-ros#61]
While checking for dependencies of one package, the RosDistroOracle can return a cryptic error : 

```
2015-10-12 16:01:48+0900 [-] Starting BuildMaster -- buildbot.version: 0.8.12
2015-10-12 16:01:48+0900 [-] Loading configuration from '/home/buildbot/buildbot-ros/master.cfg'
2015-10-12 16:02:00+0900 [-] error while parsing config file:
	Traceback (most recent call last):
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/buildbot/master.py", line 189, in startService
	    self.configFileName)
	--- <exception caught here> ---
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/buildbot/config.py", line 156, in loadConfig
	    exec f in localDict
	  File "/home/buildbot/buildbot-ros/master.cfg", line 68, in <module>
	    oracle = RosDistroOracle(rosindex, dist_names)
	  File "buildbot_ros_cfg/distro.py", line 41, in __init__
	    depends = walker.get_depends(pkg, 'buildtool')
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/rosdistro/dependency_walker.py", line 58, in get_depends
	    deps = self._get_dependencies(pkg_name, depend_type)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/rosdistro/dependency_walker.py", line 117, in _get_dependencies
	    pkg = self._get_package(pkg_name)
	  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/rosdistro/dependency_walker.py", line 52, in _get_package
	    raise InvalidPackage(pkg_name + ': %s' % str(e))
	catkin_pkg.package.InvalidPackage: gopher_navi_msgs: The manifest contains invalid XML:
	must be string or read-only buffer, not None
	
2015-10-12 16:02:00+0900 [-] Configuration Errors:
2015-10-12 16:02:00+0900 [-]   error while parsing config file: gopher_navi_msgs: The manifest contains invalid XML:
	must be string or read-only buffer, not None (traceback in logfile)
2015-10-12 16:02:00+0900 [-] Halting master.
2015-10-12 16:02:00+0900 [-] Main loop terminated.
2015-10-12 16:02:00+0900 [-] Server Shut Down.
```

Basically this this means that rosdistro couldnt get the package definition from the manifest providers it currently has. It s quite a deep rosdistro specific error, but it can be trigger by simple configuration mistakes on buildbot, and it would be very useful to have more explicit error messages when possible.

This happened to me twice already.

It always takes a long time to track down the root cause ( by debugging buildbot-ros code itself, on the same machine, which can be quite troublesome, usually just for a configuration mistake ).

**Comment by asmodehn** [comment]
I don't remember what triggered the first occurrence, but the second was because I used https:// in rosdistro for private repository (instead of a git+ssh:// ) .

**Comment by kamiccolo** [comment]
Been hitting myself this wall for months...

**Comment by mikeferguson** [comment]
I've hit this as well -- unfortunately, it really can't easily be fixed inside buildbot, since we really don't know  what went wrong -- the place to fix this would be in python-rosdistro (probably inside each manifest provider)
